name: CMake

on: [workflow_dispatch]
#on:
  #schedule:
  #- cron: '0 2 * * *' # run at 2 AM UTC

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: spmish/llvm1406:latest
      options: --user root

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DLLVM_DIR=/home/llvm-project-llvmorg-14.0.6/build/lib/cmake/llvm -DCMAKE_CXX_COMPILER=/home/llvm-project-llvmorg-14.0.6/build/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build -V

